'use client';

import { ReactNode, useEffect } from 'react';
import { I18nextProvider } from 'react-i18next';
import { DirectionProvider as RadixDirectionProvider } from '@radix-ui/react-direction';
import { I18N_LANGUAGES } from '@/i18n/config';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

// Base + chrome namespaces. Every app needs these regardless of its domain.
import faTranslations from '@/i18n/messages/fa.json';
import enTranslations from '@/i18n/messages/en.json';
import faCommon from '@/i18n/common/fa.json';
import enCommon from '@/i18n/common/en.json';
import faApiErrors from '@/i18n/api-errors/fa.json';
import enApiErrors from '@/i18n/api-errors/en.json';
import faDashboard from '@/i18n/dashboard/fa.json';
import enDashboard from '@/i18n/dashboard/en.json';

// This app's OWN namespaces. Generated by _Kit\sync-kit.ps1 from whatever lives
// in this project's i18n\ folder — do not hand-edit; re-run the sync instead.
//
// This is the one real difference from the Shell's provider. The Shell lists
// every namespace in the estate as ~100 static imports; a domain app must not,
// because those folders do not exist here. Anything missing simply falls back
// to the key's defaultValue, so a stale generated file degrades quietly rather
// than crashing.
import { DOMAIN_NAMESPACES } from '@/i18n/namespaces';

if (!i18n.isInitialized) {
  i18n
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
      resources: {
        fa: {
          translation: faTranslations,
          common: faCommon,
          'api-errors': faApiErrors,
          dashboard: faDashboard,
          ...DOMAIN_NAMESPACES.fa,
        },
        en: {
          translation: enTranslations,
          common: enCommon,
          'api-errors': enApiErrors,
          dashboard: enDashboard,
          ...DOMAIN_NAMESPACES.en,
        },
      },
      defaultNS: 'translation',
      fallbackNS: ['common', 'dashboard', 'translation'],
      lng: 'fa',
      fallbackLng: 'fa',
      debug: process.env.NODE_ENV === 'development',

      interpolation: {
        escapeValue: false,
      },

      detection: {
        order: ['localStorage', 'navigator', 'htmlTag'],
        caches: ['localStorage'],
        lookupLocalStorage: 'language',
      },

      react: {
        useSuspense: false,
      },

      initImmediate: false,
    });
}

interface I18nProviderProps {
  children: ReactNode;
}

function I18nProvider({ children }: I18nProviderProps) {
  useEffect(() => {
    const handleLanguageChange = (lng: string) => {
      const language = I18N_LANGUAGES.find((lang) => lang.code === lng);
      if (language?.direction) {
        document.documentElement.setAttribute('dir', language.direction);
      }
    };

    if (i18n.language) {
      handleLanguageChange(i18n.language);
    }

    i18n.on('languageChanged', handleLanguageChange);

    return () => {
      i18n.off('languageChanged', handleLanguageChange);
    };
  }, []);

  const currentLanguage =
    I18N_LANGUAGES.find((lang) => lang.code === (i18n.language || 'fa')) ||
    I18N_LANGUAGES[0];

  return (
    <I18nextProvider i18n={i18n}>
      <RadixDirectionProvider dir={currentLanguage.direction}>
        {children}
      </RadixDirectionProvider>
    </I18nextProvider>
  );
}

const useLanguage = () => {
  const currentLanguage =
    I18N_LANGUAGES.find((lang) => lang.code === i18n.language) || I18N_LANGUAGES[0];

  const changeLanguage = (code: string) => {
    i18n.changeLanguage(code);
  };

  return {
    languageCode: i18n.language,
    language: currentLanguage,
    changeLanguage,
  };
};

export { I18nProvider, useLanguage };
